let saveTimer = null;
async function saveGameState(immediate=false){clearTimeout(saveTimer);if(!immediate){saveTimer=setTimeout(()=>saveGameState(true),500);return}gameState.map.stage=Math.max(1,Math.min(6,Math.ceil(Number(progress||0)/17)));await putGameState(collectGameState())}
async function loadServerState(){const data=await apiRequest('/player');if(!data||!data.player)return;serverPlayer=data.player;xp=Number(data.player.xp)||0;coins=Number(data.player.coins)||0;progress=Number(data.player.progress)||0;mergeGameState(data.player.gameState);if(data.player.labStats)gameState.lab={...gameState.lab,...data.player.labStats};renderAll();renderPersistentUI()}
async function savePlayerData(){await putPlayer({xp:Number(xp)||0,coins:Number(coins)||0,progress:Number(progress)||0});await saveGameState(true)}
async function completeLessonOnServer(lessonId){const result=await apiRequest('/lessons/'+Number(lessonId)+'/complete',{method:'POST'});if(result&&result.player){serverPlayer=result.player;xp=Number(result.player.xp)||0;coins=Number(result.player.coins)||0;progress=Number(result.player.progress)||0;mergeGameState(result.player.gameState);renderAll()}return result}
async function saveByteData(byteData){if(!byteData)return;await putByte({level:Number(byteData.level)||1,bond:Number(byteData.bond)||0,energy:Number(byteData.energy)||0,state:byteData.state||'idle',memory:Array.isArray(byteData.memory)?byteData.memory:[]})}
async function saveLabData(stats){if(!stats)return;gameState.lab={...gameState.lab,...stats};await putLab({runs:Number(gameState.lab.runs)||0,successes:Number(gameState.lab.successes)||0,errors:Number(gameState.lab.errors)||0})}
function saveGameNow(){savePlayerData();saveGameState(true)}
window.addEventListener('beforeunload',()=>savePlayerData());window.addEventListener('pagehide',()=>saveGameNow());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')savePlayerData()});document.addEventListener('click',()=>setTimeout(saveGameNow,300));document.addEventListener('input',event=>{const el=event.target;if(el&&(el.tagName==='TEXTAREA'||el.tagName==='INPUT'))saveGameState()});setInterval(savePlayerData,10000);setTimeout(loadServerState,1500);setTimeout(loadServerState,3000);setTimeout(loadServerState,7000);document.addEventListener('DOMContentLoaded',async()=>{await loadServerState();renderAll();renderPersistentUI()});

async function refreshPlayerFromServer(){await loadServerState()}
setTimeout(()=>refreshPlayerFromServer(),1500);
